### ISSUE TITLE
$capsule = new \Illuminate\Database\Capsule\Manager()报错

### ISSUE THREAD

**Issue by topzar** [m9rco/Mango16#1]
我的代码是这样的，但是始终报错了
代码
`    public function _initDefaultDb(Yaf\Dispatcher $dispatcher)
    {
        Yaf\Loader::import('library/vendor/autoload.php');
        $database = Yaf\Application::app()->getConfig()->db->toArray();
        //p($database);
        // Eloquent ORM
        $capsule = new \Illuminate\Database\Capsule\Manager();
        $capsule->addConnection($database); //创建连接
        $capsule->setAsGlobal(); //设定全局静态访问
        $capsule->bootEloquent(); // 启动Eloquet
    }`

错误信息

> Warning: Yaf\Loader::autoload(): Failed opening script E:\phpStudy\WWW\yaf-framework/application\library\Illuminate\Database\Capsule\Manager.php: No such file or directory in E:\phpStudy\WWW\yaf-framework\application\Bootstrap.php on line 46

Fatal error: Class 'Illuminate\Database\Capsule\Manager' not found in E:\phpStudy\WWW\yaf-framework\application\Bootstrap.php on line 46

**Comment by m9rco** [comment]
@oyghan 稍等，已看到你的`issue`,正在全力赶往现场

**Comment by m9rco** [comment]
@oyghan 您不妨在 `library` 目录下 执行`composer update` 把
